name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
 
    steps:
 
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Checkout tools
      uses: actions/checkout@v3
      with:
        repository: arita37/myutil
        path: main

    # - name: Checkout tools repo
    #   uses: actions/checkout@v3
    #   with:
    #     path: tools

    # - name: Copy files
    #   run: |
    #     cp tools/docs/index.rst main/docs/index.rst
    #     cp tools/docs/conf.py main/docs/conf.py
    #     cp tools/docs/buildDocs.sh main/docs/buildDocs.sh

    #   shell: bash
 
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "main/docs_ghpage/buildDocs.sh"
      shell: bash
